TNW-Clone
jstloyal/TNW-clone pull request #3
Opened 2020-03-18 15:10 UTC by jstloyal

What does this PR do?

Shows how to use media queries to make a website responsive

Description of Task to be completed?

Added the HTML index file
Added CSS to style and position the element.
Ran validations on our Html and CSS.

How should this be manually tested?
Clone this branch.
open the index.html file on your browser

Screenshot
![TNW-Clone](https://user-images.githubusercontent.com/54288961/76975505-ed601600-6932-11ea-9c7d-34129eab3ce5.png)

2020-03-18 18:24 UTC, majovanilla requested changes
Hey team, 👋

## Good job on this project! 👍
- Good Readme file
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- [ ] Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors and warnings. Please fix them.

- [ ] Your sections have a lot of space between each other and that's not the case of the original page, please make them look like the source.

- [ ] Check your fonts and adjust the weight to match the titles (they should be bold) in most of your sections and articles' titles.

- [ ] See more comments below and make the required changes.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Your project would look sooo much better if you include the hover effects on the links of the page, like the original version.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-18 18:24 UTC, majovanilla commented on css/main.css
> +}
This is not the correct width. Right now your page looks smaller in width (it should occupy the whole screen). Ii should be centered, too, and it's not. Please adjust those properties to your body tag.
![Screenshot from 2020-03-18 11-51-06](https://user-images.githubusercontent.com/51926937/76991191-cabc0600-690e-11ea-852a-0a9804db4228.png)

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +                    </div>
- [ ] The logo shouldn't appear in the large breakpoint of your page.
![Screenshot from 2020-03-18 11-53-28](https://user-images.githubusercontent.com/51926937/76991949-13c08a00-6910-11ea-8f9b-6f2e46d4afab.png)

Original:
![Screenshot from 2020-03-18 11-53-34](https://user-images.githubusercontent.com/51926937/76991963-18853e00-6910-11ea-8a5a-0b6077cffd0c.png)

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +                    <h2>Latest New <i class="chevron right icon"></i></h2>
- [ ] The latest news section title should be aligned with the articles' images (both medium and large screens) and should be red.
![Screenshot from 2020-03-18 12-01-19](https://user-images.githubusercontent.com/51926937/76992109-54b89e80-6910-11ea-8cb0-09eacf773417.png)

Original:
![Screenshot from 2020-03-18 12-01-33](https://user-images.githubusercontent.com/51926937/76992126-5aae7f80-6910-11ea-8bc2-1d1484b28087.png)

- [ ] In the mobile version, your page has larger images. Please fix them.
![Screenshot from 2020-03-18 12-07-13](https://user-images.githubusercontent.com/51926937/76992582-166faf00-6911-11ea-81e5-3dd7cc127ea4.png)

Original:
![Screenshot from 2020-03-18 12-07-06](https://user-images.githubusercontent.com/51926937/76992591-1a033600-6911-11ea-8673-da9a03292a0e.png)

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +                            </div>
- [ ] All the additional-content divs should have a link inside, not a `p` element. The text should be bold. Please change it in all the section's articles.

- [ ] The `small`  tag text should be gray and have a link in the author's name.

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +                            </div>
- [ ] Check the original width and padding of the elements in this section, yours look less wide and have a lot of padding.

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +                <div class="funding">
- [ ] In the mobile version, you should only show three articles in this section. Yours has four. Please adjust this. 

- [ ] The section's articles should have 100% width when mobile. Please make this change.

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +                        <div class="app-content">
- [ ] All the articles in this section should have a larger image when in mobile screen size. Please adjust it.
![Screenshot from 2020-03-18 12-12-42](https://user-images.githubusercontent.com/51926937/76993089-ed9be980-6911-11ea-8041-da1098df49b8.png)

Original:
![Screenshot from 2020-03-18 12-12-35](https://user-images.githubusercontent.com/51926937/76993100-effe4380-6911-11ea-8174-3528484568a1.png)


- [ ] Check the original width and padding of the elements in this section, yours look less wide and they should occupy all the width of the screen.

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +                        <div class="deals-item">
- [ ] The elements in this section have a large image when in mobile screen size. 

- [ ] The title is not aligned correctly.

![Screenshot from 2020-03-18 12-16-16](https://user-images.githubusercontent.com/51926937/76993391-626f2380-6912-11ea-9afd-71139491c25a.png)

Original;
![Screenshot from 2020-03-18 12-16-10](https://user-images.githubusercontent.com/51926937/76993401-6733d780-6912-11ea-852a-aa609a7c71a1.png)

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +            </div>
- [ ] These elements should be links.

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +            </div>
- [ ] The small logos should be links.

2020-03-18 18:24 UTC, majovanilla commented on index.html
> +                        <time datetime="2020-03-13 20:00">Friday - March 13, 2020</time>
- [ ] You date is overlapping the rest of the elements when you change the screen size. Please fix this.

2020-03-19 10:39 UTC, blackpintz commented
Fixed all the errors.

2020-03-19 10:53 UTC, rOluochKe approved these changes
Hello Team
### Your project has been approved. :boom: :100: Congratulation.
### You can merge and submit the project from your dashboard. Good luck with the next project.
- Happy coding!

2020-03-19 11:02 UTC, merged